version: '3.8'

services:
  rag-api:
    build: .
    ports:
      - "8500:8500"
    volumes:
      - ./dataset:/app/dataset
    environment:
      - PYTHONPATH=/app
    command: uvicorn rag_server:app --host 0.0.0.0 --port 8500 --reload 